config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :orders
  resources :lineitems
  resources :carts

  get 'logout', to:'authentication#logout'
  post 'check_password', to: 'authentication#check_password'
  get '/login',to:'authentication#login', as: 'login'
  get 'shopper/index'
  #Change the rootpage to shopper's page
  root "shopper#index", as:"shopper"
  resources :products
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/lineitem.rb
class Lineitem < ApplicationRecord
  belongs_to :product
  belongs_to :cart
  belongs_to :order, optional:true

  def total_price_of_items
    self.product.price * self.quantity
  end

end

app/controllers/lineitems_controller.rb
class LineitemsController < ApplicationController
  include(CurrentCart)

  before_action :set_lineitem, only: %i[ show edit update destroy ]

  before_action (:set_cart)


  # GET /lineitems or /lineitems.json
  def index
    @lineitems = Lineitem.all
  end

  # GET /lineitems/1 or /lineitems/1.json
  def show
  end

  # GET /lineitems/new
  def new
    @lineitem = Lineitem.new
  end

  # GET /lineitems/1/edit
  def edit
  end

  # POST /lineitems or /lineitems.json
  def create
    #@lineitem = Lineitem.new(lineitem_params)
    #we need @cart and product to build new lineitems

    #@lineitem = @cart.lineitems.build(product_id: params[:product_id])
    @lineitem = @cart.add_item(params[:product_id])

    respond_to do |format|
      if @lineitem.save
        #format.html { redirect_to shopper_url, notice: "Lineitem was successfully created." }
        format.js
        format.json { render :show, status: :created, location: @lineitem }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @lineitem.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lineitems/1 or /lineitems/1.json
  def update
    respond_to do |format|
      if @lineitem.update(lineitem_params)
        format.html { redirect_to lineitem_url(@lineitem), notice: "Lineitem was successfully updated." }
        format.json { render :show, status: :ok, location: @lineitem }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @lineitem.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lineitems/1 or /lineitems/1.json
  def destroy
    @lineitem.destroy!

    respond_to do |format|
      format.html { redirect_to lineitems_url, notice: "Lineitem was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lineitem
      @lineitem = Lineitem.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def lineitem_params
      params.require(:lineitem).permit(:product_id, :cart_id)
    end
end

app/helpers/lineitems_helper.rb
module LineitemsHelper
end

app/views/lineitems/_form.html.erb
<%= form_with(model: lineitem) do |form| %>
  <% if lineitem.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(lineitem.errors.count, "error") %> prohibited this lineitem from being saved:</h2>

      <ul>
        <% lineitem.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :product_id, style: "display: block" %>
    <%= form.text_field :product_id %>
  </div>

  <div>
    <%= form.label :cart_id, style: "display: block" %>
    <%= form.text_field :cart_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/lineitems/_lineitem.html.erb
<div id="<%= dom_id lineitem %>">
  <p>
    <strong>Product:</strong>
    <%= lineitem.product_id %>
  </p>

  <p>
    <strong>Cart:</strong>
    <%= lineitem.cart_id %>
  </p>

</div>

app/views/lineitems/create.js.erb
document.getElementById("cart").innerHTML="<%= escape_javascript(render(@cart))%>"

app/views/lineitems/edit.html.erb
<h1>Editing lineitem</h1>

<%= render "form", lineitem: @lineitem %>

<br>

<div>
  <%= link_to "Show this lineitem", @lineitem %> |
  <%= link_to "Back to lineitems", lineitems_path %>
</div>

app/views/lineitems/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Lineitems</h1>

<div id="lineitems">
  <% @lineitems.each do |lineitem| %>
    <%= render lineitem %>
    <p>
      <%= link_to "Show this lineitem", lineitem %>
    </p>
  <% end %>
</div>

<%= link_to "New lineitem", new_lineitem_path %>

app/views/lineitems/new.html.erb
<h1>New lineitem</h1>

<%= render "form", lineitem: @lineitem %>

<br>

<div>
  <%= link_to "Back to lineitems", lineitems_path %>
</div>

app/views/lineitems/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @lineitem %>

<div>
  <%= link_to "Edit this lineitem", edit_lineitem_path(@lineitem) %> |
  <%= link_to "Back to lineitems", lineitems_path %>

  <%= button_to "Destroy this lineitem", @lineitem, method: :delete %>
</div>