config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :orders
  resources :lineitems
  resources :carts

  get 'logout', to:'authentication#logout'
  post 'check_password', to: 'authentication#check_password'
  get '/login',to:'authentication#login', as: 'login'
  get 'shopper/index'
  #Change the rootpage to shopper's page
  root "shopper#index", as:"shopper"
  resources :products
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/cart.rb
class Cart < ApplicationRecord
    has_many :lineitems, dependent: :destroy

    def add_item(product_id)
        current_item = self.lineitems.find_by(product_id: product_id)
        if current_item
            current_item.quantity += 1
        else
            current_item = self.lineitems.build(product_id: product_id)
        end
        current_item
    end

    def total_price_in_this_cart
        self.lineitems.to_a.sum do |item|
            item.total_price_of_items
        end
    end


end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: %i[ show edit update destroy ]

  # GET /carts or /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1 or /carts/1.json
  def show
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts or /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to cart_url(@cart), notice: "Cart was successfully created." }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1 or /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to cart_url(@cart), notice: "Cart was successfully updated." }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1 or /carts/1.json
  def destroy
    @cart.destroy!
    session[:cart_id] = nil

    respond_to do |format|
      format.html { redirect_to shopper_url, notice: "Cart was successfully Empty." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cart_params
      params.fetch(:cart, {})
    end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_cart.html.erb
<div id="<%= dom_id cart %>">
    <p style="color: green"><%= notice %></p>

    <h3>Items in your shopping cart</h3>

    <%#======SHOW PRODUCT IN CART ===========%>
    <table>
    <tr>
        <th>Qty</th>
        <th>Product</th>
        <th>Price</th>
    </tr>
    <% @cart.lineitems.each do |item| %>
    <tr>
        <td><%= item.quantity %></td>
        <td><%= item.product.name %> </td>
        <td><%= item.product.price%></td>
    </tr>
    <% end %>
    <tr>
        <th colspan = "2">Total</th>
        <th><%= @cart.total_price_in_this_cart %></th>
    </tr>
    </table>


    <div>

    <%= button_to "Empty this cart", @cart, method: :delete, data:{confirm:'are you sure?'} %>
    <%= button_to "Check out", new_order_path, method: :get %>
    </div>

</div>

app/views/carts/_form.html.erb
<%= form_with(model: cart) do |form| %>
  <% if cart.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
        <% cart.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing cart</h1>

<%= render "form", cart: @cart %>

<br>

<div>
  <%= link_to "Show this cart", @cart %> |
  <%= link_to "Back to carts", carts_path %>
</div>

app/views/carts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Carts</h1>

<div id="carts">
  <% @carts.each do |cart| %>
    <%= render cart %>
    <p>
      <%= link_to "Show this cart", cart %>
    </p>
  <% end %>
</div>

<%= link_to "New cart", new_cart_path %>

app/views/carts/new.html.erb
<h1>New cart</h1>

<%= render "form", cart: @cart %>

<br>

<div>
  <%= link_to "Back to carts", carts_path %>
</div>

app/views/carts/show.html.erb
<p style="color: green"><%= notice %></p>

<h3>Items in your shopping cart</h3>

<%#======SHOW PRODUCT IN CART ===========%>
<table>
  <% @cart.lineitems.each do |item| %>
  <tr>
    <td><%= item.quantity %></td>
    <td><%= item.product.name %> </td>
    <td><%= item.product.price%></td>
  </tr>
  <% end %>
  <tr>
    <td colspan = "2">Total</td>
    <td><%= @cart.total_price_in_this_cart %></td>
  </tr>
</table>


<div>

  <%= button_to "Empty this cart", @cart, method: :delete, data:{confirm:'are you sure?'} %>

</div>