config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :orders
  resources :lineitems
  resources :carts

  get 'logout', to:'authentication#logout'
  post 'check_password', to: 'authentication#check_password'
  get '/login',to:'authentication#login', as: 'login'
  get 'shopper/index'
  #Change the rootpage to shopper's page
  root "shopper#index", as:"shopper"
  resources :products
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/product.rb
class Product < ApplicationRecord
    validates(:name, :description, :image, presence:true)
    validates(:price, numericality:{greater_than_or_equal_to:0.01})
    validates(:name, uniqueness:true)
    validates(:image, format:{with: %r{\.(gif|jpg|png|jpeg)\Z}i, message:"file must be GIF, JPG, PNG, JPEG images"})

    has_many :lineitems

    before_destroy(:make_sure_no_line_items)

    def make_sure_no_line_items
        if self.lineitems.empty?
            return true
        else
            return false
        end
    end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  include (CurrentCart)
  before_action :set_product, only: %i[ show edit update destroy ]
  before_action(:set_cart)
  layout 'admin'
  # layout :det_layout

%#  def det_layout
    if session[:user_id] = nil
      'application'
    else
      'admin'
    end
  end #

  # GET /products or /products.json
  def index
    @products = Product.all
  end

  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to product_url(@product), notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to product_url(@product), notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy!

    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:name, :description, :image, :price)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_with(model: product) do |form| %>
  <% if product.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :image, style: "display: block" %>
    <%= form.text_field :image %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.text_field :price %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/products/_product.html.erb
<%# 
  <style>
    #pic {
          width: 300px;
          height: 95%;
          float: left;
          border: 1px solid black;
          padding: 2px;
      }

      img {
          width: 100%;
          height: 100%;
          object-fit: contain;
      }

      #prod {
          padding: 0px 0px 5px 0px;
          height: 180px;
      }
  </style>
%> 

<div id="<%= dom_id product %>" class="<%= cycle('list_line_odd', 'list_line_even') %>">

<div id='prod'>

 <div id='pic' >
    <%= image_tag(product.image) %>
  </div>

  <p>
    <%= product.name %>
  </p>

  <p>
    <%= product.description %>
  </p> 

  <p>
    <strong>Price:</strong>
    <%= number_to_currency(product.price) %>
  </p>
  <%= link_to "Show this product", product %>
</div>

</div>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Show this product", @product %> |
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/index.html.erb
<p style="color: green"><%= notice %></p>

<% if session[:user_id] %>
  <div>
    <%= link_to "New product", new_product_path %>
  </div>
<% end%>
<h1>Products</h1>

<div id="products">
  <% @products.each do |product| %>
    <%= render product %>
    <%#
    <p><%= link_to "Show this product", product %><%#
    </p>
    %>
  <% end %>
</div>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @product %>


<% if session[:user_id] %>
  <div>
    <%= link_to "Edit this product", edit_product_path(@product) %> |
    <%= link_to "Back to products", products_path %>
    <%= button_to "Destroy this product", @product, method: :delete %>
  </div>

  <% else %>
  <div>
      <%= button_to 'Add to Cart', lineitems_path(product_id: @product.id), class:'add_to_cart', remote: true %>
      <%= button_to 'Back to Product List', shopper_path, method: :get%>
  </div>
<% end%>